from backend.strategies.alpha import (
    news_sentiment_alpha,
    recession_indicator_alpha,
    analyst_revision_momentum,
    insider_transaction_alpha,
    post_ipo_drift_alpha,
    esg_alpha,
    short_interest_alpha,
    alternative_credit_scoring,
    web_traffic_alpha,
    sentiment_policy_alpha,
    nlp_social_alpha,
    volatility_event_driven,
    earnings_surprise_momentum,
)

from backend.strategies.diversified import (
    interest_rate_differential,
    currency_carry_trade,
    central_bank_policy_divergence,
    inflation_vs_real_rates,
    global_liquidity_cycle,
    geopolitical_hedging,
    commodity_supply_demand,
    twin_deficits_arbitrage,
    capital_flow_rotation,
    bond_term_premium,
    factor_investing,
    mean_reversion,
    volatility_arbitrage,
    dispersion_trades,
    skew_arbitrage,
    convertible_bond_arbitrage,
    credit_spread_trading,
    calendar_spreads,
    cross_asset_correlation,
    retail_vs_institutional,
    crowded_trade_unwind,
    dark_pool_sentiment,
    earnings_drift_post_reaction,
    etf_flow_alpha,
    hedge_fund_replication,
    ipo_lockup_short,
    merger_arbitrage,
    macro_surprise_index,
    metals_demand_cycle,
    oil_inventory_surprise,
    gold_vs_real_yield,
    shipping_cost_arbitrage,
    green_transition_commodities,
    livestock_spread_trade,
    seasonal_commodity_patterns,
    energy_roll_yield,
    crack_spread_trading,
    implied_volatility_premium,
    policy_sentiment_model,
    macro_regime_switching,
    multi_asset_trend_following,
)

class USMacroModel:
    def __init__(self):
        self.alpha_strategies = [
            news_sentiment_alpha,
            recession_indicator_alpha,
            analyst_revision_momentum,
            insider_transaction_alpha,
            post_ipo_drift_alpha,
            esg_alpha,
            short_interest_alpha,
            alternative_credit_scoring,
            web_traffic_alpha,
            sentiment_policy_alpha,
            nlp_social_alpha,
            volatility_event_driven,
            earnings_surprise_momentum,
        ]

        self.diversified_strategies = [
            interest_rate_differential,
            currency_carry_trade,
            central_bank_policy_divergence,
            inflation_vs_real_rates,
            global_liquidity_cycle,
            geopolitical_hedging,
            commodity_supply_demand,
            twin_deficits_arbitrage,
            capital_flow_rotation,
            bond_term_premium,
            factor_investing,
            mean_reversion,
            volatility_arbitrage,
            dispersion_trades,
            skew_arbitrage,
            convertible_bond_arbitrage,
            credit_spread_trading,
            calendar_spreads,
            cross_asset_correlation,
            retail_vs_institutional,
            crowded_trade_unwind,
            dark_pool_sentiment,
            earnings_drift_post_reaction,
            etf_flow_alpha,
            hedge_fund_replication,
            ipo_lockup_short,
            merger_arbitrage,
            macro_surprise_index,
            metals_demand_cycle,
            oil_inventory_surprise,
            gold_vs_real_yield,
            shipping_cost_arbitrage,
            green_transition_commodities,
            livestock_spread_trade,
            seasonal_commodity_patterns,
            energy_roll_yield,
            crack_spread_trading,
            implied_volatility_premium,
            policy_sentiment_model,
            macro_regime_switching,
            multi_asset_trend_following,
        ]

    def generate_signals(self, market_data):
        alpha_signals = [strategy.generate_signal(market_data) for strategy in self.alpha_strategies]
        diversified_signals = [strategy.generate_signal(market_data) for strategy in self.diversified_strategies]
        return alpha_signals + diversified_signals